# Site settings
locale: en
lang: en
title: "ashoa.github.io"
description: "Personal site for Alon Shoa"
url: "https://alonshoa.github.io"
baseurl: ""

# Theme
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

collections:
  projects:
    output: true
    permalink: /projects/:title/
  courses:
    output: true
    permalink: /teaching/:title/
  publications:
    output: true
    permalink: /research/:title/

defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: detail
      lang: en
      toc: false
  - scope:
      path: ""
      type: courses
    values:
      layout: detail
      lang: he
      toc: false
  - scope:
      path: ""
      type: publications
    values:
      layout: detail
      lang: en
      toc: false

permalink: /:categories/:title/
paginate: 5
paginate_path: "/writing/page:num/"

sass:
  sass_dir: assets/css
  style: compressed

include:
  - _pages

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules

# Navigation data is defined in _data/nav.yml
